print ("Nama  : Fitri Nidhomun N")
print ("NIM   : I0322046")
print ("Kelas : B")
print ("Halo semuanya, perkenalkan nama saya Fitri Nidhomun Ni'mah. saya biasa di panggil Nidhomun atau teman-teman bisa panggil saya juga Mumun.")
print ("saya berasal dari Boyolali. seberang kota Solo, kira-kira 1 jam menempuh perjalanan dari Solo untuk sampai di rumah saya.")
print ("Boyolali merupakan salah satu kota yang terletak di provinsi Jawa Tengah")
print ("Kabupaten ini dikenal dengan industri pertanian pariwisata, dengan beberapa tujuan wisata populer seperti Gunung Merapi, Umbul Tlatar, dll")
print ("selain itu, Boyolali juga terkenal dengan kerajinan tradisionalnya, seperti tekstil,batik, ukiran ayu, dan gerabah")
print ("sebenarnya bukan sebuah kota terpencil, tapi sering kali saya kesulitan mendapatkan sinyal ketika dirumah. entah karena minimnya tower sinyal atau karena luasnya perkebunan dan area sawah.")